name: autocorrectenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aiosignal=1.4.0
  - attrs=25.3.0
  - beautifulsoup4=4.13.4
  - frozenlist=1.7.0
  - idna=3.10
  - lxml=6.0.0
  - multidict=6.6.3
  - propcache=0.3.1
  - soupsieve=2.7
  - typing-extensions=4.14.1
  - yarl=1.20.1
  - pip
  - pybind11
